# Generated by Django 6.1.1 on 2026-10-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
