# Generated by Django 6.1.1 on 2026-10-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
